'use client'
import TranslationSentenceBySentence
  from "@/app/components/translation-sentence-by-sentence/translation-sentence-by-sentence"
import {shortDateTime, shortDate} from "@/utils/date";
import Attachment from "@/app/components/attachment/attachment";
import NavTabs from "@/app/components/nav-panel/nav-tabs";
import {
  initialState,
  translationReducer,
  TranslationContext,
  TranslationDispatchContext
} from "@/app/components/translation-view-client/translation-context";

import styles from './translation-view-client.module.css'
import {useContext, useReducer, useState} from "react";
import ClaimsTab from "@/app/components/claims-tab/claims-tab";
import OriginalTab from "@/app/components/original-tab/original-tab";
import Overlay from "@/app/components/overlay/overlay";
import Article from "@/app/components/article/article";
import Header from "@/app/components/header/header";
import AdminSection from '@/app/components/admin-section/admin-section'
import Link from "next/link";
import EditableText from "@/app/components/editable-text/editable-text";
import regenerateHeadlines from "@/app/components/translation-view-client/regenerate-headlines";
import SubscribeForm from "@/app/components/subscribe-form/subscribe-form";
export default function TranslationViewClient({translation, promptTitle,article, llm, attachment}) {
  // translation.claims.claims.map((claim,i)=>{
  //   console.log(":::::: "+i+" ::::::")
  //   for (const basedOnText of claim.basedOnText) {
  //     console.log("- "+basedOnText)
  //   }
  //   console.log("")
  // })
  const [state, dispatch] = useReducer(translationReducer, initialState)

  function dismissOriginalOverlay() {
    dispatch({
      type: 'hideOriginalOverlay'
    })
  }

  async function regenHeadlines() {
    await regenerateHeadlines(translation.id)
    window.location.reload();
  }

  return <TranslationContext.Provider value={state}>
    <TranslationDispatchContext.Provider value={dispatch}>
      <div>
        {/*<img src={`/api/translation/${translation.id}/share-image`}/>*/}
        <Header minimal={true}/>
        <article >
          <header className="article-header">
            <div className={'article-supertitle'}>
              <EditableText id={article.id} model='article' field="category">
                {article.category}
              </EditableText>
            </div>
            <h1>
              <EditableText id={article.id} model='article' field="title">
                {article.title || article.original_title}
              </EditableText>
            </h1>
            <div className="dek"><EditableText id={article.id} model='article' field="second_title">
              {article.second_title}
            </EditableText>
            </div>
            <div className="byline">
              This is an AI-written plain-English version of the {article.year} paper <span className={styles.articleLink}>&ldquo;<a
              href={article.url}>{article.original_title}</a>&rdquo;</span> by {article.attribution.trim()}.
              <br/>Written by {llm.provider} AI. Edited by <span
                className={styles.meLink}><a href={'https://www.linkedin.com/in/chrismarstall/'}>KabukiDadChris</a></span>.
              <span style={{display:'none'}}> w/ prompt '{promptTitle}'.</span>
              <AdminSection span={true}> <Link href={'#'} onClick={regenHeadlines}>regenerate headlines</Link></AdminSection>
            </div>
          </header>
          <div className="content">

            {attachment && <Attachment key={attachment.id} article={article} attachment={attachment}/>}
            <div className={styles.highlight}><span className={styles.icon}>👉</span>Click on an individual sentence to see its basis in the {article.year} study.</div>
            {/*<NavTabs/>*/}
            {state.selectedTab === 0 &&
              <TranslationSentenceBySentence translation={translation}/>}
            {state.selectedTab == 1 && <ClaimsTab article={article} translation={translation}/>}
            {state.selectedTab == 2 && <OriginalTab article={article} translation={translation}/>}
            <div style={{fontFamily: 'Arial', fontSize: 12, opacity: "75%"}}>generated by by {llm.model}
            </div>
          </div>
          <AdminSection>
            <div><Link className='button is-primary' href={`/articles/${article.id}`}>view article</Link></div>
            <div><Link className='button is-primary' href={`/articles/${article.id}/edit`}>edit article</Link></div>
            <div><Link className='button is-primary' href={`/translations/${translation.id}/edit`}>edit
              translation</Link></div>
            <div>{attachment && <Link className='button is-primary' href={`/articles/${article.id}/attachments/${attachment.id}`}>edit
              attachment</Link>}</div>
          </AdminSection>
            <SubscribeForm/>
        </article>
      </div>
      {state.originalOverlayShown && <Overlay dismiss={dismissOriginalOverlay}>
        <div className="content">
          <Article highlightClaims={state.selectedClaims} key={article.id} article={article}/>
        </div>
      </Overlay>}

    </TranslationDispatchContext.Provider>
  </TranslationContext.Provider>
}
