'use client'
import TranslationSentenceBySentence
  from "@/app/components/translation-sentence-by-sentence/translation-sentence-by-sentence"
import {shortDateTime, shortDate} from "@/utils/date";
import Attachment from "@/app/components/attachment/attachment";
import NavTabs from "@/app/components/nav-panel/nav-tabs";
import {initialState,translationReducer, TranslationContext,TranslationDispatchContext} from "@/app/components/translation-view-client/translation-context";

import styles from './translation-view-client.module.css'
import {useContext, useReducer, useState} from "react";
import ClaimsTab from "@/app/components/claims-tab/claims-tab";
import OriginalTab from "@/app/components/original-tab/original-tab";
import Overlay from "@/app/components/overlay/overlay";
import Article from "@/app/components/article/article";
import Header from "@/app/components/header/header";
import AdminSection from '@/app/components/admin-section/admin-section'
import Link from "next/link";

export default function TranslationViewClient({translation,article,llm,attachment}) {
  // translation.claims.claims.map((claim,i)=>{
  //   console.log(":::::: "+i+" ::::::")
  //   for (const basedOnText of claim.basedOnText) {
  //     console.log("- "+basedOnText)
  //   }
  //   console.log("")
  // })
  const [state,dispatch] = useReducer(translationReducer,initialState)
  function dismissOriginalOverlay() {
    dispatch({
      type: 'hideOriginalOverlay'
    })
  }
  return <TranslationContext value={state}>
    <TranslationDispatchContext value={dispatch}>
      <div>
        <Header minimal={true}/>
    <article>
      <header className="article-header">
        <div className={'article-supertitle'}>{article.category}</div>
        <h1>{article.title||article.original_title}</h1>
        <div className="dek">{article.second_title}</div>
        <div className="byline"><p>This is an AI-generated plain-english version of the {article.year} article <span
          className={"article-link"}>&ldquo;<a
          href={article.url}>{article.original_title}</a>&rdquo;</span> by {article.attribution.trim()}.
          generated by by {llm.model} {llm.type}. Click on sentences to see the correlating passages from the original paper.
        </p>
        </div>
      </header>
      <div className="article-body">
        <Attachment key={attachment.id} article={article} attachment={attachment}/>
        {/*<NavTabs/>*/}
        {state.selectedTab===0 &&
          <TranslationSentenceBySentence translation={translation}/>}
        {state.selectedTab==1 && <ClaimsTab article={article} translation={translation}/>}
        {state.selectedTab==2 && <OriginalTab article={article} translation={translation}/>}
        <div style={{fontFamily:'Arial',fontSize:12,opacity:"75%"}}>generated by by {llm.model}
        </div>
      </div>
      <AdminSection>
        <div><Link className='button is-primary' href={`/articles/${article.id}`}>edit article</Link></div>
        <div><Link className='button is-primary' href={`/translations/${translation.id}/edit`}>edit translation</Link></div>
        <div><Link className='button is-primary' href={`/articles/${article.id}/attachments/${attachment.id}`}>edit attachment</Link></div>
      </AdminSection>
    </article>
      </div>
      {state.originalOverlayShown &&<Overlay dismiss={dismissOriginalOverlay}>
        <div className="content">
        <Article highlightClaims={state.selectedClaims} key={article.id} article={article}/>
        </div>
      </Overlay>}

    </TranslationDispatchContext>
  </TranslationContext>
}
